name: quote_of_the_day
description: A Quote of the Day App.

environment:
  sdk: ">=3.0.0 <5.0.0"

dependencies:
  flutter:
    sdk: flutter
  share_plus: ^4.0.2
  shared_preferences: ^2.0.18


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

share_plus: ^6.3.0

  
